services:
  db:
    image: mariadb:10.11
    container_name: pokemon_torneio_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: pokemon123
    ports:
      - "3306:3306"
    volumes:
      - ./inicializar/1_esquema.sql:/docker-entrypoint-initdb.d/1_esquema.sql:ro
      - ./scripts/2_popular.sql:/docker-entrypoint-initdb.d/2_popular.sql:ro
      - ./scripts/3_trigger.sql:/docker-entrypoint-initdb.d/3_trigger.sql:ro
      - ./scripts/3_triggerAtivado.sql:/docker-entrypoint-initdb.d/3_triggerAtivado.sql:ro
      - ./consultas/4_visao1.sql:/docker-entrypoint-initdb.d/4_visao1.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
